// app/dashboard/relatorios/ManualReport.tsx
// Seção de relatório manual com escolha de período + indicadores e geração de PDF.
// Não depende do WhatsApp — o usuário pega o PDF e baixa/imprime localmente.
'use client'

import { useState, useEffect } from 'react'
import { useActiveOrgId } from '@/lib/AuthContext'
import { supabase } from '@/lib/supabase'
import { Loader2, FileText, Printer, Calendar as CalendarIcon, Download } from 'lucide-react'
import CustomSelect from '@/app/dashboard/components/CustomSelect'

// ═══════════════════════════════════════════════════════════════════════════════
// TRADUÇÕES
// ═══════════════════════════════════════════════════════════════════════════════

type Lang = 'pt' | 'en' | 'es'

const T = {
  pt: {
    title: 'Relatório Manual',
    subtitle: 'Escolha o período e os indicadores que quer ver. Gera um PDF pronto pra baixar.',
    from: 'De',
    to: 'Até',
    quickRange: 'Atalho',
    rangeToday: 'Hoje',
    rangeYesterday: 'Ontem',
    range7: 'Últimos 7 dias',
    range30: 'Últimos 30 dias',
    rangeMonth: 'Este mês',
    rangeLastMonth: 'Mês passado',
    rangeCustom: 'Personalizado',
    indicators: 'Indicadores',
    selectAll: 'Todos',
    clearAll: 'Limpar',
    // categorias de indicadores
    operationalCat: 'Operacional',
    m_leads_captados: 'Contatos captados',
    m_canais_origem: 'Canais de origem',
    m_mensagens_enviadas: 'Mensagens enviadas',
    m_leads_responderam: 'Contatos que responderam',
    pipelineCat: 'Pipeline',
    m_pipeline: 'Distribuição por etapa (foto atual)',
    m_pipeline_flow: 'Movimentações por etapa (fluxo do período)',
    m_user_activity: 'Atividade por responsável',
    financialCat: 'Financeiro',
    m_receita: 'Receita total',
    m_despesas: 'Despesas totais',
    m_lucro: 'Lucro líquido',
    m_negocios: 'Negócios fechados',
    m_ticket_medio: 'Ticket médio',
    m_comissoes: 'Comissões pendentes',
    siteCat: 'Site público',
    m_site_views: 'Visualizações',
    m_site_leads: 'Leads do site',
    m_site_conversion: 'Taxa de conversão',
    goalsCat: 'Metas',
    m_meta_principal: 'Meta principal ativa',
    // ações
    generate: 'Gerar Relatório',
    generating: 'Gerando...',
    print: 'Baixar / Imprimir PDF',
    // preview
    previewTitle: 'Pré-visualização',
    noDataHint: 'Selecione pelo menos um indicador.',
    period: 'Período',
    generatedAt: 'Gerado em',
    footerNote: 'Relatório gerado pelo Oryen Systems',
    errorGeneric: 'Erro ao gerar relatório',
    closePreview: 'Fechar',
  },
  en: {
    title: 'Manual Report',
    subtitle: 'Pick a range and the KPIs you want. We generate a PDF ready to download.',
    from: 'From',
    to: 'To',
    quickRange: 'Shortcut',
    rangeToday: 'Today',
    rangeYesterday: 'Yesterday',
    range7: 'Last 7 days',
    range30: 'Last 30 days',
    rangeMonth: 'This month',
    rangeLastMonth: 'Last month',
    rangeCustom: 'Custom',
    indicators: 'Indicators',
    selectAll: 'All',
    clearAll: 'Clear',
    operationalCat: 'Operational',
    m_leads_captados: 'Leads captured',
    m_canais_origem: 'Source channels',
    m_mensagens_enviadas: 'Messages sent',
    m_leads_responderam: 'Leads that responded',
    pipelineCat: 'Pipeline',
    m_pipeline: 'Distribution per stage (current snapshot)',
    m_pipeline_flow: 'Transitions per stage (flow in period)',
    m_user_activity: 'Activity per team member',
    financialCat: 'Financial',
    m_receita: 'Total revenue',
    m_despesas: 'Total expenses',
    m_lucro: 'Net profit',
    m_negocios: 'Deals closed',
    m_ticket_medio: 'Average ticket',
    m_comissoes: 'Pending commissions',
    siteCat: 'Public site',
    m_site_views: 'Page views',
    m_site_leads: 'Site leads',
    m_site_conversion: 'Conversion rate',
    goalsCat: 'Goals',
    m_meta_principal: 'Active main goal',
    generate: 'Generate Report',
    generating: 'Generating...',
    print: 'Download / Print PDF',
    previewTitle: 'Preview',
    noDataHint: 'Select at least one indicator.',
    period: 'Period',
    generatedAt: 'Generated at',
    footerNote: 'Report generated by Oryen Systems',
    errorGeneric: 'Error generating report',
    closePreview: 'Close',
  },
  es: {
    title: 'Informe Manual',
    subtitle: 'Elige el período y los indicadores. Generamos un PDF listo para descargar.',
    from: 'Desde',
    to: 'Hasta',
    quickRange: 'Atajo',
    rangeToday: 'Hoy',
    rangeYesterday: 'Ayer',
    range7: 'Últimos 7 días',
    range30: 'Últimos 30 días',
    rangeMonth: 'Este mes',
    rangeLastMonth: 'Mes pasado',
    rangeCustom: 'Personalizado',
    indicators: 'Indicadores',
    selectAll: 'Todos',
    clearAll: 'Limpiar',
    operationalCat: 'Operacional',
    m_leads_captados: 'Contactos captados',
    m_canais_origem: 'Canales de origen',
    m_mensagens_enviadas: 'Mensajes enviados',
    m_leads_responderam: 'Contactos que respondieron',
    pipelineCat: 'Pipeline',
    m_pipeline: 'Distribución por etapa (foto actual)',
    m_pipeline_flow: 'Transiciones por etapa (flujo del período)',
    m_user_activity: 'Actividad por responsable',
    financialCat: 'Financiero',
    m_receita: 'Ingresos totales',
    m_despesas: 'Gastos totales',
    m_lucro: 'Beneficio neto',
    m_negocios: 'Negocios cerrados',
    m_ticket_medio: 'Ticket promedio',
    m_comissoes: 'Comisiones pendientes',
    siteCat: 'Sitio público',
    m_site_views: 'Visualizaciones',
    m_site_leads: 'Leads del sitio',
    m_site_conversion: 'Tasa de conversión',
    goalsCat: 'Metas',
    m_meta_principal: 'Meta principal activa',
    generate: 'Generar Informe',
    generating: 'Generando...',
    print: 'Descargar / Imprimir PDF',
    previewTitle: 'Vista previa',
    noDataHint: 'Selecciona al menos un indicador.',
    period: 'Período',
    generatedAt: 'Generado el',
    footerNote: 'Informe generado por Oryen Systems',
    errorGeneric: 'Error al generar informe',
    closePreview: 'Cerrar',
  },
}

// ═══════════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════════

function isoDate(d: Date): string {
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

function getPresetRange(preset: string): { from: string; to: string } {
  const today = new Date()
  today.setHours(0, 0, 0, 0)

  if (preset === 'today') {
    const s = isoDate(today)
    return { from: s, to: s }
  }
  if (preset === 'yesterday') {
    const y = new Date(today)
    y.setDate(today.getDate() - 1)
    const s = isoDate(y)
    return { from: s, to: s }
  }
  if (preset === '7') {
    const s = new Date(today)
    s.setDate(today.getDate() - 6)
    return { from: isoDate(s), to: isoDate(today) }
  }
  if (preset === '30') {
    const s = new Date(today)
    s.setDate(today.getDate() - 29)
    return { from: isoDate(s), to: isoDate(today) }
  }
  if (preset === 'month') {
    const s = new Date(today.getFullYear(), today.getMonth(), 1)
    return { from: isoDate(s), to: isoDate(today) }
  }
  if (preset === 'lastMonth') {
    const s = new Date(today.getFullYear(), today.getMonth() - 1, 1)
    const e = new Date(today.getFullYear(), today.getMonth(), 0)
    return { from: isoDate(s), to: isoDate(e) }
  }
  // fallback: hoje
  const s = isoDate(today)
  return { from: s, to: s }
}

function formatCurrency(value: number, currency: string, lang: string) {
  try {
    return new Intl.NumberFormat(lang === 'en' ? 'en-US' : lang === 'es' ? 'es-ES' : 'pt-BR', {
      style: 'currency',
      currency: currency || 'BRL',
    }).format(value || 0)
  } catch {
    return String(value)
  }
}

function formatInt(value: number, lang: string) {
  return new Intl.NumberFormat(lang === 'en' ? 'en-US' : lang === 'es' ? 'es-ES' : 'pt-BR').format(value || 0)
}

// ═══════════════════════════════════════════════════════════════════════════════
// COMPONENTE
// ═══════════════════════════════════════════════════════════════════════════════

interface ManualReportProps {
  lang: Lang
}

export default function ManualReport({ lang }: ManualReportProps) {
  const activeOrgId = useActiveOrgId()
  const t = T[lang]

  // Range: padrão = últimos 7 dias
  const initial = getPresetRange('7')
  const [rangePreset, setRangePreset] = useState<string>('7')
  const [from, setFrom] = useState(initial.from)
  const [to, setTo] = useState(initial.to)

  // Pipeline stages da org (pra permitir seleção de "distribuição por etapa")
  const [pipelineStageIds, setPipelineStageIds] = useState<string[]>([])

  // Indicadores selecionados
  const [picked, setPicked] = useState({
    // operacional
    leads_captados: true,
    canais_origem: true,
    mensagens_enviadas: true,
    leads_responderam: true,
    // pipeline (on/off; se on, usa TODAS as stages ativas)
    pipeline: true,
    pipeline_flow: true,   // fluxo de transições dentro do período
    user_activity: true,   // atividade por responsável
    // financeiro
    receita: false,
    despesas: false,
    lucro: false,
    negocios: false,
    ticket_medio: false,
    comissoes: false,
    // site
    site_views: false,
    site_leads: false,
    site_conversion: false,
    // goals
    meta_principal: false,
  })

  const [generating, setGenerating] = useState(false)
  const [reportData, setReportData] = useState<any | null>(null)
  const [error, setError] = useState<string | null>(null)

  // Carrega pipeline_stages ativas pra incluir no relatório quando pipeline=true
  useEffect(() => {
    if (!activeOrgId) return
    supabase
      .from('pipeline_stages')
      .select('id')
      .eq('org_id', activeOrgId)
      .eq('is_active', true)
      .then(({ data }) => setPipelineStageIds((data || []).map((r: any) => r.id)))
  }, [activeOrgId])

  const handlePreset = (preset: string) => {
    setRangePreset(preset)
    if (preset === 'custom') return
    const r = getPresetRange(preset)
    setFrom(r.from)
    setTo(r.to)
  }

  const toggle = (key: keyof typeof picked) => {
    setPicked(prev => ({ ...prev, [key]: !prev[key] }))
  }

  const selectAll = () => {
    const next: any = {}
    Object.keys(picked).forEach(k => { next[k] = true })
    setPicked(next)
  }

  const clearAll = () => {
    const next: any = {}
    Object.keys(picked).forEach(k => { next[k] = false })
    setPicked(next)
  }

  const anySelected = Object.values(picked).some(Boolean)

  const handleGenerate = async () => {
    setError(null)
    if (!anySelected) {
      setError(t.noDataHint)
      return
    }
    setGenerating(true)
    try {
      const metrics = {
        base: {
          leads_captados: picked.leads_captados,
          canais_origem: picked.canais_origem,
          mensagens_enviadas: picked.mensagens_enviadas,
          leads_responderam: picked.leads_responderam,
        },
        pipeline: picked.pipeline ? pipelineStageIds : [],
        pipeline_flow: picked.pipeline_flow,
        user_activity: picked.user_activity,
        financial: {
          receita: picked.receita,
          despesas: picked.despesas,
          lucro: picked.lucro,
          negocios: picked.negocios,
          ticket_medio: picked.ticket_medio,
          comissoes: picked.comissoes,
        },
        site: {
          views: picked.site_views,
          site_leads: picked.site_leads,
          conversion: picked.site_conversion,
        },
        goals: {
          meta_principal: picked.meta_principal,
        },
        followup: {},
      }

      const res = await fetch('/api/reports/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ from, to, metrics }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error || t.errorGeneric)
      setReportData(json.data)
    } catch (err: any) {
      setError(err.message || t.errorGeneric)
    } finally {
      setGenerating(false)
    }
  }

  const handlePrint = () => {
    if (!reportData) return
    const printWindow = window.open('', '_blank')
    if (!printWindow) return
    printWindow.document.write(buildPrintHtml(reportData, t, lang))
    printWindow.document.close()
    // Pequeno delay pro browser renderizar antes de imprimir
    setTimeout(() => printWindow.print(), 300)
  }

  return (
    <div className="rounded-2xl p-5 sm:p-6" style={{ background: 'var(--color-bg-elevated)', border: '1px solid var(--color-border)' }}>
      {/* Header */}
      <div className="flex items-start gap-3 mb-5">
        <div className="p-2.5 rounded-xl shrink-0" style={{ background: 'var(--color-primary-subtle)', color: 'var(--color-primary)' }}>
          <FileText size={20} />
        </div>
        <div>
          <h2 className="text-lg font-bold" style={{ color: 'var(--color-text-primary)' }}>{t.title}</h2>
          <p className="text-sm mt-0.5" style={{ color: 'var(--color-text-secondary)' }}>{t.subtitle}</p>
        </div>
      </div>

      {/* Controles */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-5">
        <div>
          <label className="block text-xs font-semibold mb-1.5" style={{ color: 'var(--color-text-secondary)' }}>{t.quickRange}</label>
          <CustomSelect
            value={rangePreset}
            onChange={handlePreset}
            options={[
              { value: 'today', label: t.rangeToday },
              { value: 'yesterday', label: t.rangeYesterday },
              { value: '7', label: t.range7 },
              { value: '30', label: t.range30 },
              { value: 'month', label: t.rangeMonth },
              { value: 'lastMonth', label: t.rangeLastMonth },
              { value: 'custom', label: t.rangeCustom },
            ]}
          />
        </div>
        <div>
          <label className="block text-xs font-semibold mb-1.5" style={{ color: 'var(--color-text-secondary)' }}>{t.from}</label>
          <input
            type="date"
            value={from}
            onChange={e => { setFrom(e.target.value); setRangePreset('custom') }}
            className="w-full px-3 py-2.5 rounded-lg text-sm outline-none"
            style={{ background: 'var(--color-bg-base)', border: '1px solid var(--color-border)', color: 'var(--color-text-primary)' }}
          />
        </div>
        <div>
          <label className="block text-xs font-semibold mb-1.5" style={{ color: 'var(--color-text-secondary)' }}>{t.to}</label>
          <input
            type="date"
            value={to}
            onChange={e => { setTo(e.target.value); setRangePreset('custom') }}
            className="w-full px-3 py-2.5 rounded-lg text-sm outline-none"
            style={{ background: 'var(--color-bg-base)', border: '1px solid var(--color-border)', color: 'var(--color-text-primary)' }}
          />
        </div>
      </div>

      {/* Indicadores */}
      <div className="mb-5">
        <div className="flex items-center justify-between mb-3">
          <label className="text-sm font-bold" style={{ color: 'var(--color-text-primary)' }}>{t.indicators}</label>
          <div className="flex gap-2">
            <button onClick={selectAll} className="text-xs font-medium px-2 py-1 rounded" style={{ color: 'var(--color-primary)', background: 'var(--color-primary-subtle)' }}>{t.selectAll}</button>
            <button onClick={clearAll} className="text-xs font-medium px-2 py-1 rounded" style={{ color: 'var(--color-text-secondary)', background: 'var(--color-bg-hover)', border: '1px solid var(--color-border)' }}>{t.clearAll}</button>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <CategoryBlock title={t.operationalCat}>
            <Chk label={t.m_leads_captados} checked={picked.leads_captados} onToggle={() => toggle('leads_captados')} />
            <Chk label={t.m_canais_origem} checked={picked.canais_origem} onToggle={() => toggle('canais_origem')} />
            <Chk label={t.m_mensagens_enviadas} checked={picked.mensagens_enviadas} onToggle={() => toggle('mensagens_enviadas')} />
            <Chk label={t.m_leads_responderam} checked={picked.leads_responderam} onToggle={() => toggle('leads_responderam')} />
          </CategoryBlock>

          <CategoryBlock title={t.pipelineCat}>
            <Chk label={t.m_pipeline} checked={picked.pipeline} onToggle={() => toggle('pipeline')} />
            <Chk label={t.m_pipeline_flow} checked={picked.pipeline_flow} onToggle={() => toggle('pipeline_flow')} />
            <Chk label={t.m_user_activity} checked={picked.user_activity} onToggle={() => toggle('user_activity')} />
          </CategoryBlock>

          <CategoryBlock title={t.financialCat}>
            <Chk label={t.m_receita} checked={picked.receita} onToggle={() => toggle('receita')} />
            <Chk label={t.m_despesas} checked={picked.despesas} onToggle={() => toggle('despesas')} />
            <Chk label={t.m_lucro} checked={picked.lucro} onToggle={() => toggle('lucro')} />
            <Chk label={t.m_negocios} checked={picked.negocios} onToggle={() => toggle('negocios')} />
            <Chk label={t.m_ticket_medio} checked={picked.ticket_medio} onToggle={() => toggle('ticket_medio')} />
            <Chk label={t.m_comissoes} checked={picked.comissoes} onToggle={() => toggle('comissoes')} />
          </CategoryBlock>

          <CategoryBlock title={t.siteCat}>
            <Chk label={t.m_site_views} checked={picked.site_views} onToggle={() => toggle('site_views')} />
            <Chk label={t.m_site_leads} checked={picked.site_leads} onToggle={() => toggle('site_leads')} />
            <Chk label={t.m_site_conversion} checked={picked.site_conversion} onToggle={() => toggle('site_conversion')} />
          </CategoryBlock>

          <CategoryBlock title={t.goalsCat}>
            <Chk label={t.m_meta_principal} checked={picked.meta_principal} onToggle={() => toggle('meta_principal')} />
          </CategoryBlock>
        </div>
      </div>

      {error && (
        <p className="text-sm mb-3" style={{ color: 'var(--color-error)' }}>{error}</p>
      )}

      {/* Ação de gerar */}
      <button
        onClick={handleGenerate}
        disabled={generating}
        className="w-full flex items-center justify-center gap-2 px-5 py-3 rounded-xl text-sm font-bold transition-all disabled:opacity-60 shadow-sm"
        style={{ background: 'var(--color-primary)', color: '#fff' }}
      >
        {generating ? (
          <>
            <Loader2 size={16} className="animate-spin" />
            {t.generating}
          </>
        ) : (
          <>
            <FileText size={16} />
            {t.generate}
          </>
        )}
      </button>

      {/* Preview */}
      {reportData && (
        <div className="mt-5 rounded-xl p-4 sm:p-5" style={{ background: 'var(--color-bg-base)', border: '1px solid var(--color-border)' }}>
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-sm font-bold" style={{ color: 'var(--color-text-primary)' }}>{t.previewTitle}</h3>
            <div className="flex gap-2">
              <button
                onClick={handlePrint}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors"
                style={{ background: 'var(--color-success-subtle)', color: 'var(--color-success)', border: '1px solid var(--color-success)' }}
              >
                <Download size={12} />
                {t.print}
              </button>
              <button
                onClick={() => setReportData(null)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium"
                style={{ background: 'var(--color-bg-hover)', color: 'var(--color-text-secondary)', border: '1px solid var(--color-border)' }}
              >
                {t.closePreview}
              </button>
            </div>
          </div>

          <ReportPreview data={reportData} t={t} lang={lang} />
        </div>
      )}
    </div>
  )
}

// ═══════════════════════════════════════════════════════════════════════════════
// Subcomponentes
// ═══════════════════════════════════════════════════════════════════════════════

function CategoryBlock({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl p-3" style={{ background: 'var(--color-bg-base)', border: '1px solid var(--color-border)' }}>
      <p className="text-[10px] font-bold uppercase tracking-wider mb-2" style={{ color: 'var(--color-text-muted)' }}>{title}</p>
      <div className="space-y-1">{children}</div>
    </div>
  )
}

function Chk({ label, checked, onToggle }: { label: string; checked: boolean; onToggle: () => void }) {
  return (
    <label className="flex items-center gap-2 cursor-pointer text-sm" style={{ color: 'var(--color-text-secondary)' }}>
      <input type="checkbox" checked={checked} onChange={onToggle} className="cursor-pointer" />
      <span>{label}</span>
    </label>
  )
}

function ReportPreview({ data, t, lang }: { data: any; t: any; lang: Lang }) {
  const rows: { label: string; value: string }[] = []

  if (data.leads_captados !== undefined) rows.push({ label: t.m_leads_captados, value: formatInt(data.leads_captados, lang) })
  if (data.leads_responderam !== undefined) rows.push({ label: t.m_leads_responderam, value: formatInt(data.leads_responderam, lang) })
  if (data.mensagens_enviadas !== undefined) rows.push({ label: t.m_mensagens_enviadas, value: formatInt(data.mensagens_enviadas, lang) })
  if (data.receita_total !== undefined) rows.push({ label: t.m_receita, value: formatCurrency(data.receita_total, data.currency, lang) })
  if (data.despesas_total !== undefined) rows.push({ label: t.m_despesas, value: formatCurrency(data.despesas_total, data.currency, lang) })
  if (data.lucro_liquido !== undefined) rows.push({ label: t.m_lucro, value: formatCurrency(data.lucro_liquido, data.currency, lang) })
  if (data.negocios_fechados !== undefined) rows.push({ label: t.m_negocios, value: formatInt(data.negocios_fechados, lang) })
  if (data.ticket_medio !== undefined) rows.push({ label: t.m_ticket_medio, value: formatCurrency(data.ticket_medio, data.currency, lang) })
  if (data.comissoes_pendentes !== undefined) rows.push({ label: t.m_comissoes, value: formatCurrency(data.comissoes_pendentes, data.currency, lang) })
  if (data.site_views !== undefined) rows.push({ label: t.m_site_views, value: formatInt(data.site_views, lang) })
  if (data.site_leads !== undefined) rows.push({ label: t.m_site_leads, value: formatInt(data.site_leads, lang) })
  if (data.site_conversion !== undefined) rows.push({ label: t.m_site_conversion, value: `${data.site_conversion.toFixed(1)}%` })

  return (
    <div>
      <p className="text-xs mb-2" style={{ color: 'var(--color-text-muted)' }}>
        <strong>{t.period}:</strong> {data.period}
      </p>
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 mb-3">
        {rows.map((r, i) => (
          <div key={i} className="rounded-lg p-2.5" style={{ background: 'var(--color-bg-surface)', border: '1px solid var(--color-border)' }}>
            <p className="text-[10px] font-semibold uppercase tracking-wider" style={{ color: 'var(--color-text-muted)' }}>{r.label}</p>
            <p className="text-base font-bold mt-0.5" style={{ color: 'var(--color-text-primary)' }}>{r.value}</p>
          </div>
        ))}
      </div>

      {data.canais_origem && data.canais_origem.length > 0 && (
        <div className="mt-3">
          <p className="text-xs font-bold mb-2" style={{ color: 'var(--color-text-secondary)' }}>{t.m_canais_origem}</p>
          <div className="space-y-1 text-xs" style={{ color: 'var(--color-text-secondary)' }}>
            {data.canais_origem.map((c: any, i: number) => (
              <div key={i} className="flex items-center justify-between">
                <span>{c.name}</span>
                <span className="font-bold">{c.count}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.pipeline && data.pipeline.length > 0 && (
        <div className="mt-3">
          <p className="text-xs font-bold mb-2" style={{ color: 'var(--color-text-secondary)' }}>{t.m_pipeline}</p>
          <div className="space-y-1 text-xs" style={{ color: 'var(--color-text-secondary)' }}>
            {data.pipeline.map((p: any, i: number) => (
              <div key={i} className="flex items-center justify-between">
                <span>{p.label}</span>
                <span className="font-bold">{p.count}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.pipeline_flow && data.pipeline_flow.length > 0 && (
        <div className="mt-3">
          <p className="text-xs font-bold mb-2" style={{ color: 'var(--color-text-secondary)' }}>{t.m_pipeline_flow}</p>
          <div className="space-y-1 text-xs" style={{ color: 'var(--color-text-secondary)' }}>
            {data.pipeline_flow.map((p: any, i: number) => (
              <div key={i} className="flex items-center justify-between">
                <span>→ {p.label}</span>
                <span className="font-bold">{p.count}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.user_activity && data.user_activity.length > 0 && (
        <div className="mt-3">
          <p className="text-xs font-bold mb-2" style={{ color: 'var(--color-text-secondary)' }}>{t.m_user_activity}</p>
          <div className="overflow-x-auto">
            <table className="w-full text-xs" style={{ color: 'var(--color-text-secondary)' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--color-border)' }}>
                  <th className="text-left py-1.5 pr-3 font-semibold">{lang === 'en' ? 'Member' : lang === 'es' ? 'Miembro' : 'Membro'}</th>
                  <th className="text-right py-1.5 px-1 font-semibold">{t.m_leads_captados}</th>
                  <th className="text-right py-1.5 px-1 font-semibold">{lang === 'en' ? 'Stage' : 'Etapa'}</th>
                  <th className="text-right py-1.5 px-1 font-semibold">{lang === 'en' ? 'Calls' : lang === 'es' ? 'Llam.' : 'Ligaç.'}</th>
                  <th className="text-right py-1.5 px-1 font-semibold">{lang === 'en' ? 'Meetings' : lang === 'es' ? 'Reun.' : 'Reun./Visitas'}</th>
                  <th className="text-right py-1.5 px-1 font-semibold">{lang === 'en' ? 'Proposals' : lang === 'es' ? 'Propuestas' : 'Propostas'}</th>
                  <th className="text-right py-1.5 pl-1 font-bold" style={{ color: 'var(--color-text-primary)' }}>{lang === 'en' ? 'Total' : 'Total'}</th>
                </tr>
              </thead>
              <tbody>
                {data.user_activity.map((u: any, i: number) => (
                  <tr key={i} style={{ borderBottom: '1px solid var(--color-border-subtle)' }}>
                    <td className="py-1.5 pr-3">{u.user_name}</td>
                    <td className="text-right py-1.5 px-1">{u.leads_created}</td>
                    <td className="text-right py-1.5 px-1">{u.stage_changes}</td>
                    <td className="text-right py-1.5 px-1">{u.calls_made}</td>
                    <td className="text-right py-1.5 px-1">{u.meetings_attended}</td>
                    <td className="text-right py-1.5 px-1">{u.proposals_sent}</td>
                    <td className="text-right py-1.5 pl-1 font-bold" style={{ color: 'var(--color-text-primary)' }}>{u.total}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {data.meta_principal_nome && (
        <div className="mt-3 rounded-lg p-2.5" style={{ background: 'var(--color-bg-surface)', border: '1px solid var(--color-border)' }}>
          <p className="text-xs font-bold" style={{ color: 'var(--color-text-secondary)' }}>{t.m_meta_principal}</p>
          <p className="text-sm" style={{ color: 'var(--color-text-primary)' }}>
            {data.meta_principal_nome}: <strong>{formatInt(data.meta_principal_progresso || 0, lang)} / {formatInt(data.meta_principal_target || 0, lang)}</strong>
          </p>
        </div>
      )}
    </div>
  )
}

// ═══════════════════════════════════════════════════════════════════════════════
// PDF template (abre em janela nova e dispara print)
// ═══════════════════════════════════════════════════════════════════════════════

function buildPrintHtml(data: any, t: any, lang: Lang): string {
  const rows: { label: string; value: string }[] = []

  if (data.leads_captados !== undefined) rows.push({ label: t.m_leads_captados, value: formatInt(data.leads_captados, lang) })
  if (data.leads_responderam !== undefined) rows.push({ label: t.m_leads_responderam, value: formatInt(data.leads_responderam, lang) })
  if (data.mensagens_enviadas !== undefined) rows.push({ label: t.m_mensagens_enviadas, value: formatInt(data.mensagens_enviadas, lang) })
  if (data.receita_total !== undefined) rows.push({ label: t.m_receita, value: formatCurrency(data.receita_total, data.currency, lang) })
  if (data.despesas_total !== undefined) rows.push({ label: t.m_despesas, value: formatCurrency(data.despesas_total, data.currency, lang) })
  if (data.lucro_liquido !== undefined) rows.push({ label: t.m_lucro, value: formatCurrency(data.lucro_liquido, data.currency, lang) })
  if (data.negocios_fechados !== undefined) rows.push({ label: t.m_negocios, value: formatInt(data.negocios_fechados, lang) })
  if (data.ticket_medio !== undefined) rows.push({ label: t.m_ticket_medio, value: formatCurrency(data.ticket_medio, data.currency, lang) })
  if (data.comissoes_pendentes !== undefined) rows.push({ label: t.m_comissoes, value: formatCurrency(data.comissoes_pendentes, data.currency, lang) })
  if (data.site_views !== undefined) rows.push({ label: t.m_site_views, value: formatInt(data.site_views, lang) })
  if (data.site_leads !== undefined) rows.push({ label: t.m_site_leads, value: formatInt(data.site_leads, lang) })
  if (data.site_conversion !== undefined) rows.push({ label: t.m_site_conversion, value: `${data.site_conversion.toFixed(1)}%` })

  const safe = (s: string) => String(s || '').replace(/</g, '&lt;').replace(/>/g, '&gt;')

  const rowsHtml = rows.map(r => `
    <div class="kpi">
      <div class="kpi-label">${safe(r.label)}</div>
      <div class="kpi-value">${safe(r.value)}</div>
    </div>
  `).join('')

  const channelsHtml = (data.canais_origem && data.canais_origem.length > 0) ? `
    <section>
      <h3>${safe(t.m_canais_origem)}</h3>
      <table>
        <tbody>
          ${data.canais_origem.map((c: any) => `
            <tr><td>${safe(c.name)}</td><td style="text-align:right"><strong>${c.count}</strong></td></tr>
          `).join('')}
        </tbody>
      </table>
    </section>
  ` : ''

  const pipelineHtml = (data.pipeline && data.pipeline.length > 0) ? `
    <section>
      <h3>${safe(t.m_pipeline)}</h3>
      <table>
        <tbody>
          ${data.pipeline.map((p: any) => `
            <tr><td>${safe(p.label)}</td><td style="text-align:right"><strong>${p.count}</strong></td></tr>
          `).join('')}
        </tbody>
      </table>
    </section>
  ` : ''

  const pipelineFlowHtml = (data.pipeline_flow && data.pipeline_flow.length > 0) ? `
    <section>
      <h3>${safe(t.m_pipeline_flow)}</h3>
      <table>
        <tbody>
          ${data.pipeline_flow.map((p: any) => `
            <tr><td>→ ${safe(p.label)}</td><td style="text-align:right"><strong>${p.count}</strong></td></tr>
          `).join('')}
        </tbody>
      </table>
    </section>
  ` : ''

  const userActivityHtml = (data.user_activity && data.user_activity.length > 0) ? `
    <section>
      <h3>${safe(t.m_user_activity)}</h3>
      <table class="activity">
        <thead>
          <tr>
            <th align="left">${lang === 'en' ? 'Member' : lang === 'es' ? 'Miembro' : 'Membro'}</th>
            <th align="right">${safe(t.m_leads_captados)}</th>
            <th align="right">${lang === 'en' ? 'Stage changes' : lang === 'es' ? 'Cambios etapa' : 'Mud. etapa'}</th>
            <th align="right">${lang === 'en' ? 'Calls' : lang === 'es' ? 'Llamadas' : 'Ligações'}</th>
            <th align="right">${lang === 'en' ? 'Meetings' : lang === 'es' ? 'Reuniones' : 'Reuniões/Visitas'}</th>
            <th align="right">${lang === 'en' ? 'Proposals' : lang === 'es' ? 'Propuestas' : 'Propostas'}</th>
            <th align="right">${lang === 'en' ? 'Notes' : lang === 'es' ? 'Notas' : 'Notas'}</th>
            <th align="right"><strong>Total</strong></th>
          </tr>
        </thead>
        <tbody>
          ${data.user_activity.map((u: any) => `
            <tr>
              <td>${safe(u.user_name)}</td>
              <td align="right">${u.leads_created}</td>
              <td align="right">${u.stage_changes}</td>
              <td align="right">${u.calls_made}</td>
              <td align="right">${u.meetings_attended}</td>
              <td align="right">${u.proposals_sent}</td>
              <td align="right">${u.notes_added}</td>
              <td align="right"><strong>${u.total}</strong></td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </section>
  ` : ''

  const goalHtml = data.meta_principal_nome ? `
    <section>
      <h3>${safe(t.m_meta_principal)}</h3>
      <p><strong>${safe(data.meta_principal_nome)}:</strong> ${formatInt(data.meta_principal_progresso || 0, lang)} / ${formatInt(data.meta_principal_target || 0, lang)}</p>
    </section>
  ` : ''

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<title>${safe(data.reportName)} — ${safe(data.orgName)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 11pt;
    color: #1a1a1a;
    background: #fff;
    padding: 20mm;
    line-height: 1.5;
  }
  header {
    border-bottom: 2px solid #0f172a;
    padding-bottom: 12px;
    margin-bottom: 20px;
  }
  header h1 { font-size: 20pt; color: #0f172a; margin-bottom: 4px; }
  header .meta { font-size: 10pt; color: #4b5563; }
  .kpi-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 10px;
    margin-bottom: 20px;
  }
  .kpi {
    border: 1px solid #e5e7eb;
    border-radius: 8px;
    padding: 12px;
    background: #f9fafb;
  }
  .kpi-label {
    font-size: 8pt;
    font-weight: 600;
    color: #6b7280;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    margin-bottom: 4px;
  }
  .kpi-value {
    font-size: 14pt;
    font-weight: 700;
    color: #0f172a;
  }
  section { margin-bottom: 18px; page-break-inside: avoid; }
  section h3 {
    font-size: 12pt;
    color: #0f172a;
    margin-bottom: 8px;
    padding-bottom: 4px;
    border-bottom: 1px solid #e5e7eb;
  }
  table { width: 100%; border-collapse: collapse; }
  table td, table th {
    padding: 6px 8px;
    border-bottom: 1px solid #f1f5f9;
    font-size: 10pt;
  }
  table.activity th {
    font-size: 8.5pt;
    font-weight: 600;
    color: #4b5563;
    text-transform: uppercase;
    letter-spacing: 0.3px;
    border-bottom: 2px solid #e5e7eb;
  }
  footer {
    margin-top: 30px;
    padding-top: 12px;
    border-top: 1px solid #e5e7eb;
    font-size: 9pt;
    color: #9ca3af;
    text-align: center;
  }
  @media print {
    body { padding: 10mm; }
  }
</style>
</head>
<body>
  <header>
    <h1>${safe(data.orgName)}</h1>
    <div class="meta">
      <strong>${safe(data.reportName)}</strong><br/>
      ${safe(t.period)}: ${safe(data.period)} &middot; ${safe(t.generatedAt)}: ${safe(data.generatedAt)}
    </div>
  </header>

  ${rowsHtml ? `<div class="kpi-grid">${rowsHtml}</div>` : ''}
  ${channelsHtml}
  ${pipelineHtml}
  ${pipelineFlowHtml}
  ${userActivityHtml}
  ${goalHtml}

  <footer>
    ${safe(t.footerNote)}
  </footer>
</body>
</html>`
}
